_wandb:
    value:
        cli_version: 0.22.2
        e:
            wda0xr7hi83bbmgmmyy3t19jzcwauie4:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "9663676416"
                args:
                    - run
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "197909114880"
                email: emiliacywinskaWS@gmail.com
                executable: /Users/emiliacywinska/miniforge3/envs/asi-ml/bin/python3.11
                git:
                    commit: c42ddbc0e2c6d919cefcce18422020829e30076a
                    remote: https://github.com/Dzzzuma/Asi2025.git
                host: macbook-air-emilia.home
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/emiliacywinska/miniforge3/envs/asi-ml/bin/kedro
                python: CPython 3.11.14
                root: /Users/emiliacywinska/Desktop/studia/ROK 4/ASI/Asi2025/Asi2025
                startedAt: "2025-11-10T10:54:58.292314Z"
                writerId: wda0xr7hi83bbmgmmyy3t19jzcwauie4
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
kind:
    value: logreg
max_iter:
    value: 5000
